
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsgbptmfvyhpfpefdbsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZ2JwdG1mdnlocGZwZWZkYnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTc3ODcsImV4cCI6MjA2MjQ5Mzc4N30.ApkfBvGQNDsafT6CF1B_QO9Kg0i4gy07JKVbin3T29U";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
